INSERT INTO typevoyage (LIBELLE, DESCRIPTION) VALUES ("Circuit", ""),
    ("Séjour", ""),
    ("Croisière", "");
INSERT INTO prestation (LIBELLE, DESCRIPTION) VALUES ("Transfert", ""),
    ("Hotel", ""),
    ("Restaurant", ""),
    ("Service/Accueil", ""),
    ("Animation", ""),
    ("Excursions/Guide", ""),
    ("Transport aerien", ""),
    ("Transport car", ""),
    ("Thalasso/SPA", ""),
    ("Croisiere", "");
INSERT INTO utilisateur (NOM, MDP) VALUES ("admin", "$2y$10$cKD52jszt5utE1ozipFsMOzbqRqYmjQCi0w1j/XIsdkylmrp7uZ82");